# Generated by Django 5.1.5 on 2025-01-22 22:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('renda_familiar', models.FloatField(help_text='Renda total da família em reais')),
                ('num_membros', models.PositiveIntegerField(help_text='Número de membros na família')),
                ('despesas_mensais', models.FloatField(help_text='Despesas mensais da família em reais')),
                ('nivel_escolaridade', models.CharField(choices=[('FUND', 'Ensino Fundamental'), ('MED', 'Ensino Médio'), ('SUP', 'Ensino Superior'), ('POS', 'Pós-graduação'), ('OUT', 'Outro')], max_length=50)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Data', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
