# Generated by Django 5.1.5 on 2025-01-30 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_perfil_genero'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='situacao_emprego',
            field=models.CharField(choices=[('EMPREGADO', 'Empregado'), ('DESEMPREGADO', 'Desempregado'), ('AUTONOMO', 'Autônomo'), ('APOSENTADO', 'Aposentado')], default=123, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='data',
            name='tipo_moradia',
            field=models.CharField(choices=[('ALUGADA', 'Alugada'), ('PROPRIA', 'Própria'), ('CEDIDA', 'Cedida'), ('INVADIDA', 'Invadida')], default=123, max_length=20),
            preserve_default=False,
        ),
    ]
